### ISSUE TITLE
Link to github project - student assigment

### ISSUE THREAD

**Issue by eamador1** [eamador1/capstone-js#21]
The link to the capstone project is https://github.com/eamador1/capstone-js

There are three people in this group:
Student A is @donice
Student B is  @Idvl777
Student C is @eamador1

**Comment by topeogunleye** [comment]
Hi @eamador1, @donice 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a kanban project, that doesn't provide information on the number of people in this group. Example:

"There are X number of people in this group"

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by anagudelogu** [comment]
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @eamador1 @donice @Idvl777, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub's project features! 🥇 

## Required Changes ♻️
_Check the comments under the review._

### Assignees 👷🏼 

- [ ] According to the requirements:

![Screenshot from 2023-09-05 09-31-02](https://github.com/eamador1/capstone-js/assets/77069011/75440a91-c1c9-49f7-a118-e3c8be5b4633)

Please make sure that all cards on your kanban have assignees! 🤓 🔧 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @eamador1, @gdvl777 and @donice,

✔️ Tasks are complete and well-assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
